import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const tools=[
 {name:'tk_up_prepare',description:'Prepare a resumable job requiring nine Codex-generated 800x800 PNG images.',inputSchema:{type:'object',required:['workspace_root','product_folder'],properties:{workspace_root:{type:'string'},product_folder:{type:'string'},sku:{type:'string'}}}},
 {name:'tk_up_status',description:'Show image readiness for a TK-UP job.',inputSchema:{type:'object',required:['job_id','workspace_root'],properties:{job_id:{type:'string'},workspace_root:{type:'string'}}}},
 {name:'tk_up_finalize',description:'Verify exactly nine 800x800 PNGs and then write only a copied matched category template.',inputSchema:{type:'object',required:['job_id','workspace_root','generated_images','category','listing'],properties:{job_id:{type:'string'},workspace_root:{type:'string'},generated_images:{type:'array',items:{type:'string'}},category:{type:'string'},listing:{type:'object'}}}}
];
function send(x){let b=JSON.stringify(x);process.stdout.write(`Content-Length: ${Buffer.byteLength(b)}\r\n\r\n${b}`)}
function fail(s){throw Error(s)}
function jp(root,id){return path.join(root,'.tk-up','jobs',id+'.json')}
function png800(f){let b=fs.readFileSync(f);return b.subarray(0,8).toString('hex')==='89504e470d0a1a0a'&&b.length>=24&&b.readUInt32BE(16)===800&&b.readUInt32BE(20)===800}
function template(root,category){let line=fs.readFileSync(path.join(root,'muban','类目.md'),'utf8').split(/\r?\n/).find(x=>x.includes(category));let n=line?.match(/<!--\s*([^<>]+?\.xlsx)\s*-->/)?.[1]?.trim();if(!n)fail('No template mapping for category; no workbook was written.');let p=path.join(root,'muban','leimu',n);if(!fs.existsSync(p))fail('Mapped template is missing; no workbook was written.');return p}
function run(n,a){
 if(n==='tk_up_prepare'){let root=path.resolve(a.workspace_root),folder=path.resolve(a.product_folder);if(!fs.existsSync(folder))fail('Product folder not found.');let id=crypto.randomUUID(), d=path.dirname(jp(root,id));fs.mkdirSync(d,{recursive:true});let job={id,workspace_root:root,product_folder:folder,sku:a.sku||path.basename(folder),state:'awaiting_images',expected_images:Array.from({length:9},(_,i)=>`image-${i+1}.png`)};fs.writeFileSync(jp(root,id),JSON.stringify(job,null,2));return {job_id:id,state:job.state,requirement:'Use Codex image_gen for exactly nine local 800x800 PNGs. This server does not use an API or generate images.'}}
 let file=jp(a.workspace_root,a.job_id);if(!fs.existsSync(file))fail('Job not found.');let j=JSON.parse(fs.readFileSync(file,'utf8'));
 if(n==='tk_up_status')return {job_id:j.id,state:j.state,verified_images:j.generated_images?.length||0,missing:9-(j.generated_images?.length||0),workbook:j.workbook||null};
 if(n!=='tk_up_finalize')fail('Unknown tool.');let images=a.generated_images;if(!Array.isArray(images)||images.length!==9)fail('Image gate failed: exactly 9 images required; no workbook was written.');let u=[...new Set(images.map(x=>path.resolve(x)))];if(u.length!==9||u.some(f=>path.extname(f).toLowerCase()!=='.png'||!fs.existsSync(f)||!png800(f)))fail('Image gate failed: all 9 must be distinct 800x800 PNG files; no workbook was written.');
 let t=template(j.workspace_root,a.category), sku=(j.sku||'product').replace(/[<>:"/\\|?*]/g,'_'), out=path.join(j.workspace_root,'类目模板输出',path.basename(t,'.xlsx'),`${sku}_${path.basename(t)}`);fs.mkdirSync(path.dirname(out),{recursive:true});let r=spawnSync('python',[path.join(path.dirname(fileURLToPath(import.meta.url)),'write_template_row.py'),t,out,JSON.stringify(a.listing)],{encoding:'utf8'});if(r.status)fail(r.stderr||r.stdout||'Template write failed.');j.state='finalized';j.generated_images=u;j.category=a.category;j.workbook=out;fs.writeFileSync(file,JSON.stringify(j,null,2));return {job_id:j.id,state:j.state,workbook:out,template:t};
}
let buf=Buffer.alloc(0);process.stdin.on('data',c=>{buf=Buffer.concat([buf,c]);for(;;){let k=buf.indexOf('\r\n\r\n');if(k<0)return;let n=+(/content-length:\s*(\d+)/i.exec(buf.subarray(0,k).toString())||[])[1],s=k+4;if(!n||buf.length<s+n)return;let q=JSON.parse(buf.subarray(s,s+n));buf=buf.subarray(s+n);try{if(q.method==='initialize')send({jsonrpc:'2.0',id:q.id,result:{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'tk-up',version:'0.1.0'}}});else if(q.method==='tools/list')send({jsonrpc:'2.0',id:q.id,result:{tools}});else if(q.method==='tools/call')send({jsonrpc:'2.0',id:q.id,result:{content:[{type:'text',text:JSON.stringify(run(q.params.name,q.params.arguments||{}))}]}});else send({jsonrpc:'2.0',id:q.id,error:{code:-32601,message:'Unknown method'}})}catch(e){send({jsonrpc:'2.0',id:q.id,error:{code:-32000,message:e.message}})}}});
